const Handlebars = require('handlebars');
const fs = require('fs');
const path = require('path');

function generateTextReport(videos, stats) {
  let report = `🎬 YouTube Shorts Viral Report\n${new Date().toISOString().split('T')[0]}\n\n`;
  report += `📊 SUMMARY\n`;
  report += `- Videos Searched: ${stats.totalFound}\n`;
  report += `- Viral Hits: ${stats.totalFiltered}\n`;
  report += `- Already Reported: ${stats.duplicatesRemoved}\n\n`;
  
  if (videos.length === 0) {
    report += `No videos met your criteria today.\n`;
    report += `Check back tomorrow for new trending content!\n`;
  } else {
    report += `🔥 TRENDING VIDEOS\n${'─'.repeat(50)}\n\n`;
    
    videos.forEach((v, i) => {
      report += `${i + 1}. ${v.title}\n`;
      report += `   👤 ${v.channelTitle}\n`;
      report += `   👁  ${v.viewCount.toLocaleString()} views\n`;
      report += `   ❤️  ${v.likeCount.toLocaleString()} likes\n`;
      report += `   📈 ${v.engagementRate}% engagement\n`;
      report += `   ⏰ ${v.ageHours}h ago\n`;
      report += `   🔗 ${v.videoUrl}\n\n`;
    });
  }
  
  report += `\n${'─'.repeat(50)}\n`;
  report += `Filter Criteria:\n`;
  report += `• 20K+ views | 2%+ like ratio | 3%+ engagement | 24h max age\n`;
  report += `Generated by YouTube Shorts Automation\n`;
  
  return report;
}

function generateHtmlReport(videos, stats) {
  const templateSource = fs.readFileSync(path.join(__dirname, 'emailTemplate.hbs'), 'utf8');
  const template = Handlebars.compile(templateSource);
  
  return template({
    date: new Date().toISOString().split('T')[0],
    videos,
    stats
  });
}

module.exports = {
  generateTextReport,
  generateHtmlReport
};
